version: 0.2

phases:
  install:
    runtime-version:
      java: corretoll
  pre_build:
    commands:
      - echo nothing to do in the pre_build phase...
  build:
    commands:
      - echo build started on `date`
      - mvn package
  post_build:
    commands:
      - echo build completed on `date`
artifacts:
  files:
    - target/*.war
